site_name: Keeplight
site_url: https://keeplight.io
repo_url: https://github.com/keeplight/documentation
repo_name: 'GitHub'
site_author: Nick Sjostrom
pages:
  - Home: index.md
  - User Guide:
    - 'Sites': 'user/sites.md'
    - 'Assets': 'user/assets.md'
    - 'Settings': 'user/settings.md'
  - Developer:
    - 'Sessions': 'api/session.md'
    - 'Sites': 'api/sites.md'
    - 'Assets': 'api/assets.md'
  - About: about.md
theme: readthedocs