site_name: Keeplight
pages:
  - Home: index.md
  - User Guide:
    - 'Sites': 'user/sites.md'
    - 'Assets': 'user/assets.md'
    - 'Settings': 'user/settings.md'
  - Developer:
    - 'Sessions': 'api/session.md'
    - 'Sites': 'api/sites.md'
    - 'Assets': 'api/assets.md'
  - About: about.md
theme: readthedocs